version: '3'

services:
  traefik:
    build: dockerfiles/traefik/
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
      - frontend

  beeper:
    build: .
    command: /bin/bash
    ports:
      - "5001:5001"
    depends_on:
      - beeping
      - elastic
    labels:
      - "traefik.enable=true"
      - "traefik.backend=beeper"
      - "traefik.frontend.rule=Host:beeper.example.com"
    networks:
      - backend

  default:
    image: nginx:1
    ports:
      - "80"
    volumes:
      - ./dockerfiles/default/html:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.backend=default"
      - "traefik.frontend.rule=Host:default.example.com"
    networks:
      - backend

  beeping:
    image: doubtingben/beeping:1
    environment:
      - BEEPING_LISTEN=0.0.0.0
    ports:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=beeping"
      - "traefik.frontend.rule=Host:beeping.example.com"
    networks:
      - backend

  elastic:
    image: elasticsearch:5
    ports:
      - "9200"
    volumes:
      - ./dockerfiles/elasticsearch/5/conf/jvm.options:/srv/elasticsearch/config/jvm.options
      - ./dockerfiles/elasticsearch/5/conf/elasticsearch.yml:/srv/elasticsearch/config/elasticsearch.yml
    labels:
      - "traefik.enable=true"
      - "traefik.backend=elastic"
      - "traefik.frontend.rule=Host:elastic.example.com"
    networks:
      - backend

  cerebro:
    image: yannart/cerebro:0.6.5
    ports:
      - "9000"
    links:
      - "elastic:elasticsearch"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=cerebro"
      - "traefik.frontend.rule=Host:cerebro.example.com"
    networks:
      - backend

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=cadvisor"
      - "traefik.frontend.rule=Host:cadvisor.example.com"
    networks:
      - backend

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
      - "9090"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=prometheus"
      - "traefik.frontend.rule=Host:prometheus.example.com"
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
